version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: store
    environment:
      NODE_ENV: production
      MONGO_URI: "YOUR_MONGO_URI"
      secretOrKey: "tacotruck34872394"
    ports:
      - "5000:5000"